export const ngo = [
    {
        logo: '/public/NGO logo.jpg',
        id: "avvd",
        name: 'Robin Hood Army',
        address: 'New Delhi, Delhi',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Trust',
        desc: 'Sectors Working in: Culture, Biotechnology, Children, Dalit Upliftment, Differently Abled, Disaster Management, Drinking Water, Education & Literacy, Environment & Forests, Food Processing, HIV/AIDS'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "avcd",
        name: 'Project Humanity',
        address: 'Jorhat, Assam',
        followers: '2k+',
        volunteers: '100+',
        drills: '20+',
        type: 'Trust',
        desc: 'Sectors Working in: Food, Blood, Public Welfare'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "fds",
        name: 'GLOBAL IMPERIAL FOUNDATION TRUST',
        address: 'New Delhi, Delhi',
        followers: '5k+',
        volunteers: '500+',
        drills: '19+',
        type: 'Trust',
        desc: 'Sectors Working in: Agriculture,Art & Culture,Biotechnology,Children,Dalit Upliftment,Differently Abled,Disaster Management,Drinking Water,Education & Literacy,Environment & Forests,Food Processing'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "asdf",
        name: 'Aasmaan Foundation',
        address: 'Ahmedabad,Gujarat',
        followers: '1k+',
        volunteers: '100+',
        drills: '20+',
        type: 'Trust',
        desc: 'Sectors Working in: Children,Education & Literacy'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "ifn",
        name: 'AABASAHEB CHIMANRAO PATIL LOKWANGMAYA GRANTHALAYAy',
        address: 'Parola, Maharashtra',
        followers: '8k+',
        volunteers: '120+',
        drills: '20+',
        type: 'Society',
        desc: 'Sectors Working in: Art & Culture,Education & Literacy'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "wqw",
        name: 'AAS WELFARE SOCIETY',
        address: 'Mohali, Punjab',
        followers: '15k+',
        volunteers: '1200+',
        drills: '35+',
        type: 'Society',
        desc: 'Sectors Working in:Children,Education & Literacy,Health & Family Welfare,Rural Development & Poverty Alleviation,Vocational Training'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "tyb",
        name: 'ABHINASH SOCIO ECONOMIC VOLUNTARY ORGANISATION',
        address: 'Bhubaneswar, Orissa',
        followers: '20k+',
        volunteers: '500+',
        drills: '30+',
        type: 'Society',
        desc: 'Sectors Working in: Agriculture'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "uvw",
        name: 'RADHAKANTA ES INSTITUTE OF COMPUTER TECHNOLOGY',
        address: '	Baleswar, Orissa',
        followers: '15k+',
        volunteers: '800+',
        drills: '25+',
        type: 'Trust',
        desc: 'Sectors Working in:Vocational Training'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "pim",
        name: 'A CHIK BAPTIST CONVENTION',
        address: 'Bongaigaon, Assam',
        followers: '1k+',
        volunteers: '200+',
        drills: '10+',
        type: 'Trust',
        desc: 'Sectors Working in: Agriculture,Children,Education & Literacy,Health & Family Welfare'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "nbvc",
        name: 'AADYA SRISHTI KALA MANDIR CULTURAL SOCIETY',
        address: 'Tinsukia, Assam',
        followers: '5k+',
        volunteers: '200+',
        drills: '12+',
        type: 'Socity',
        desc: 'Sectors Working in: Art & Culture,Children,Education & Literacy,Environment & Forests,Rural Development & Poverty Alleviation'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "yhn",
        name: '2A BUSINESS TOTALITY PRIVATE LIMITED',
        address: 'Chennai, Tamil Nadu',
        followers: '30k+',
        volunteers: '1000+',
        drills: '50+',
        type: ' Sector 8 Company',
        desc: 'Sectors Working in: Agriculture,Education & Literacy,Food Processing,Health & Family Welfare,Human Rights,Information & Communication Technology,Labour & Employment,Legal Awareness & Aid,New & Renewable Energy,Sports,Vocational Training,'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "mrnf",
        name: 'AA Edutech Pvt Ltd',
        address: 'Chennai, Tamil Nadu',
        followers: '15k+',
        volunteers: '400+',
        drills: '30+',
        type: 'Trust',
        desc: 'Sectors Working in: Culture, Biotechnology, Children, Dalit Upliftment, Differently Abled, Disaster Management, Drinking Water, Education & Literacy, Environment & Forests, Food Processing, HIV/AIDS'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "cnrg",
        name: 'AA Edutech Pvt Ltd',
        address: 'Chennai, Tamil Nadu',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Sector 8 Company',
        desc: 'Sectors Working in: Education & Literacy'
    },{
        logo: '/public/NGO logo.jpg',
        id: "dkgj",
        name: 'Sita Jain Memorial Trust',
        address: 'Kolkata, West Bengal',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Trust',
        desc: 'Sectors Working in: Children'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "edc",
        name: 'Help Us Help Them',
        address: 'Kolkata, West Bengal',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Society',
        desc: 'Sectors Working in: Children,Education & Literacy'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "jkl",
        name: 'RAJA BHAIYA FOUNDATION',
        address: 'Vaishali, Bihar',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Sector 8 company',
        desc: 'Sectors Working in:Aged/Elderly,Rural Development & Poverty Alleviation,Skill Development,Education & Literacy'
    },
    {
        logo: '/public/NGO logo.jpg',
        id: "uytr",
        name: '3S Security Services',
        address: 'Indore, Madhya Pradesh',
        followers: '10k+',
        volunteers: '200+',
        drills: '20+',
        type: 'Trust',
        desc: 'Sectors Working in: Labour & Employment,Vocational Training,Any Other'
    },
    ]